name: Comprobar servicio de Render

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Solicitar ruta de salud
        run: curl --fail --show-error --silent --retry 5 --retry-all-errors --retry-delay 10 --max-time 70 https://novamarket.onrender.com/health
